import type { WidgetPreset } from "@/lib/types";

export const WIDGET_PRESETS: WidgetPreset[] = [
  {
    key: "countdown-default",
    label: "Countdown Timer",
    widget_id: "countdown",
    title: "Countdown Timer",
    size: "1x2",
    config: {
      label: "Next release",
      target_time: new Date(Date.now() + 1000 * 60 * 90).toISOString(),
    },
  },
  {
    key: "sports-ipl",
    label: "IPL Live",
    widget_id: "sports",
    title: "IPL Live",
    size: "4x2",
    config: {
      sport: "ipl",
      provider: "auto",
      tournament: "IPL",
      competition_code: "PL",
      refresh_behavior: "auto",
      refresh_interval_seconds: 120,
      cache_ttl_seconds: 90,
    },
  },
  {
    key: "sports-f1",
    label: "F1 Session",
    widget_id: "sports",
    title: "F1 Session",
    size: "4x2",
    config: {
      sport: "f1",
      provider: "auto",
      tournament: "IPL",
      competition_code: "PL",
      refresh_behavior: "auto",
      refresh_interval_seconds: 120,
      cache_ttl_seconds: 90,
    },
  },
  {
    key: "sports-football",
    label: "Football Watch",
    widget_id: "sports",
    title: "Football Watch",
    size: "4x2",
    config: {
      sport: "football",
      provider: "auto",
      tournament: "IPL",
      competition_code: "PL",
      refresh_behavior: "auto",
      refresh_interval_seconds: 120,
      cache_ttl_seconds: 90,
    },
  },
  {
    key: "news-default",
    label: "News Radar",
    widget_id: "news",
    title: "News Radar",
    size: "2x2",
    config: {
      provider: "rss",
      topic: "openclaw",
      feed_urls: ["https://news.ycombinator.com/rss", "https://www.theverge.com/rss/index.xml"],
      refresh_behavior: "interval",
      refresh_interval_seconds: 600,
      cache_ttl_seconds: 300,
      limit: 5,
      language: "en",
    },
  },
  {
    key: "trending-default",
    label: "Trend Stack",
    widget_id: "trending",
    title: "Trend Stack",
    size: "2x4",
    config: {
      sources: ["reddit", "x", "hackernews"],
      subreddit: "technology",
      reddit_listing: "hot",
      x_query: "technology OR ai",
      hn_story_type: "top",
      refresh_behavior: "interval",
      refresh_interval_seconds: 300,
      cache_ttl_seconds: 120,
      limit: 5,
    },
  },
  {
    key: "pinboard-default",
    label: "Personal Pinboard",
    widget_id: "pinboard",
    title: "Personal Pinboard",
    size: "2x4",
    config: {
      notes: [
        { id: "1", text: "Drop in a new note and it persists in the widget config." },
      ],
    },
  },
];
